#! /bin/sh

AESDPAR="-d"
case "$1" in
	start)
		echo "Starting aesdsocket"
		start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket $AESDPAR
		;;
	stop)
		echo "Stopping aesdserver"
		start-stop-daemon -K aesdsocket
		;;
	*)
		echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
