#!/bin/sh

start() {
	echo "Starting init scripts for loading kernel modules..."
    # Add commands to load your kernel modules here
    /usr/bin/aesdchar_load
}

stop() {
	echo "Starting init scripts for unloading kernel modules..."
    # Add commands to unload your kernel modules here
    /usr/bin/aesdchar_unload
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  *)
    echo "Usage: $0 {start|stop}"
  exit 1
esac

exit 0
